server:
  port: 8083
spring:
  application:
    name: AutoFlow

  datasource:
    url: jdbc:postgresql://localhost:5432/AutoFlowBD
    username: postgres
    password: AutoFlow2026!

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        format_sql: true